# Generated by Django 4.2.3 on 2023-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('review_text', models.CharField(max_length=500)),
                ('review_number', models.IntegerField()),
                ('review_image', models.ImageField(upload_to='images/')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
