# Generated by Django 4.2.3 on 2023-07-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_applications', '0002_review_account_review_imt_id_review_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='size',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
