# Generated by Django 4.2.3 on 2023-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_applications', '0003_alter_review_review_image_alter_review_review_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.IntegerField(default=None)),
                ('payment_qr', models.BooleanField(default=False, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.IntegerField(default=None)),
                ('address_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='buy_articles',
            field=models.JSONField(default=None, null=True),
        ),
    ]
