# Generated by Django 4.2.3 on 2023-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_applications', '0004_account_address_review_buy_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='buy_articles',
        ),
        migrations.AddField(
            model_name='account',
            name='buy_articles',
            field=models.JSONField(default=None, null=True),
        ),
    ]
