# Generated by Django 4.2.3 on 2023-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_applications', '0005_remove_review_buy_articles_account_buy_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='buy_articles',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_name',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
