# Generated by Django 4.2.3 on 2023-07-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_applications', '0012_ransoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='ransoms',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
